# Generated by Django 3.0.5 on 2020-06-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Location',
            field=models.CharField(default=0, max_length=2083),
            preserve_default=False,
        ),
    ]
